### ISSUE TITLE
llama.cpp /Compat = true troubleshooting for "function": " Unterminated string..."

### ISSUE THREAD

**Issue by kratosok** [itsme2417/PolyMind#10]
"It's designed to be used with Mixtral 8x7B-Instruct/Mistral-7B-Instruct-v0.2 + TabbyAPI, but can be used with other models and/or with llama.cpp's included server and, when using the compatiblity mode + tabbyAPI mode, any endpoint with /v1/completions support"

I run alot of models with localai.io which provides openai compatible endpoints. I'm having a little trouble running polymind with it, so I thought I'd get your insight.

Here's the head of my config.json:
    "Backend": "llama.cpp",
    "compatibility_mode": true,
    "compat_tokenizer_model":"/fastdata/langmodels/mistralai_Mistral-7B-Instruct-v0.1",
    "HOST": "localhost",
    "PORT": 8881,
    "admin_ip": "127.0.0.1",

When I send in a request, I get:
```
192.168.144.167 - - [31/Mar/2024 15:31:46] "GET /stream HTTP/1.1" 200 -
192.168.144.167 - - [31/Mar/2024 15:31:46] "GET /chat_history HTTP/1.1" 200 -
Begin streamed GateKeeper output.
Token count: 561


[{
  "function": "
Unterminated string starting at: line 3 column 15 (char 18)
Token count: 118

192.168.144.167 - - [31/Mar/2024 15:31:56] "POST / HTTP/1.1" 200 -
```

**Comment by itsme2417** [comment]
llama.cpp backend mode is only for the api server included in llama.cpp which uses a custom non openai compatible api endpoint, so compatibility mode does nothing in that combination. For localai.io you would use compatibility_mode set to true and backend set to tabbyapi

**Comment by kratosok** [comment]
Thanks for the info, weirdly I still get a similiar error with tabbyapi set as the backend:

```
192.168.144.167 - - [31/Mar/2024 22:08:10] "GET /stream HTTP/1.1" 200 -
initializing memory
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET / HTTP/1.1" 200 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/@highlightjs/cdn-assets/styles/default.min.css HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/marked/lib/marked.umd.js HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/marked-highlight/lib/index.umd.js HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/@highlightjs/cdn-assets/highlight.min.js HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /static/node_modules/darkreader/darkreader.js HTTP/1.1" 304 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /stream HTTP/1.1" 200 -
192.168.144.167 - - [31/Mar/2024 22:08:20] "GET /chat_history HTTP/1.1" 200 -
Begin streamed GateKeeper output.
Token count: 561


[{
  "function": "
Unterminated string starting at: line 3 column 15 (char 18)
Token count: 118

192.168.144.167 - - [31/Mar/2024 22:08:56] "POST / HTTP/1.1" 200 -
```

**Comment by kratosok** [comment]
Just an update, I loaded the project with Vscode and stepped through it. The error came in for me because Localai.io lets you specify what model name to run. The project defaults to "gpt-3.5-turbo-instruct", which I didn't have a model defined for that in localai. I have changed my localai configuration and it is running now.
