### ISSUE TITLE
Output comes on the next page

### ISSUE THREAD

**Issue by aloksaurabh** [itsme2417/PolyMind#4]
See pictures 
Image1
![Screenshot 2024-01-31 195330](https://github.com/itsme2417/PolyMind/assets/7407336/36fb2c7e-8a8c-4c12-983b-2a3eceb77d7f)
Image2
![Screenshot 2024-01-31 195352](https://github.com/itsme2417/PolyMind/assets/7407336/80efb9a5-aeb5-4d83-afc7-554b3fbeef00)

**Comment by itsme2417** [comment]
Have you done step 3 of the installation process? 
`Install the required node modules: cd static && npm install`

**Comment by aloksaurabh** [comment]
My bad

**Comment by aloksaurabh** [comment]
solved with cd static && npm install
