### ISSUE TITLE
Example config.json with local tokenizer?

### ISSUE THREAD

**Issue by kratosok** [itsme2417/PolyMind#8]
Any example config.json with local tokenzier?

I feel like i'm close to getting this to running locally which is exciting, but i'm not sure what local tokenizer to use with my local installation. I'm trying to connect Ooba as the backend api on 5000 so I can easily try a couple of different models.

![image](https://github.com/itsme2417/PolyMind/assets/2236179/4bc3d30c-3d71-4fea-b7c0-2e763a673aa5)
![image](https://github.com/itsme2417/PolyMind/assets/2236179/bb1c1ea1-a2f0-4118-895f-4892570f031d)

**Comment by itsme2417** [comment]
For the tokenizer model, you can just put the model you are using, for example "mistralai/Mixtral-8x7B-Instruct-v0.1" for mixtral / mixtral based models.

**Comment by kratosok** [comment]
Thanks! I think I got the tokenizer worked out:
    "Backend": "tabbyapi",
    "compatibility_mode": true,
    "compat_tokenizer_model":"/langmodels/mistralai_Mistral-7B-Instruct-v0.1",
    "HOST": "127.0.0.1",
    "PORT": 5000,
    "admin_ip": "127.0.0.1",
    "listen": true,
    "api_key": "",
    "max_seq_len": 16000,
    "reserve_space": true,
    


But now when i launch python main.py it just silently quits.
(polymind) [user@brainbox PolyMind]$ python main.py
Loaded config
(polymind) [user@brainbox PolyMind]$ nano config.json

**Comment by itsme2417** [comment]
Fixed in [c2e4b46](https://github.com/itsme2417/PolyMind/commit/c2e4b46e1e163b1243ca9fb0c91e1a8a2c23656d)
